image: atlassian/default-image:2

pipelines:
  branches:
    production:
      - step:
          name: Build image
          services:
            - docker
          script:
            - export IMAGE_NAME=mishakalmah/json-compare:$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME
      - step:
          name: Deploy production
          deployment: production
          script:
            - export IMAGE_NAME=mishakalmah/json-compare:$BITBUCKET_COMMIT
            - ssh -tt deploy@jsoncompare.ru ./deploy -i $IMAGE_NAME -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
